<a href="https://colab.research.google.com/github/santhoshkumar81740/Information-and-Retrieval-Systems-Lab/blob/main/PageRank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import xml.etree.ElementTree as ET
import numpy as np

# -----------------------------
# XML input
# -----------------------------
xml_data = """
<web>
    <page name="A">
        <link>B</link>
        <link>C</link>
    </page>

    <page name="B">
        <link>C</link>
        <link>D</link>
    </page>

    <page name="C">
        <link>A</link>
    </page>

    <page name="D">
        <link>C</link>
        <link>A</link>
    </page>
</web>
"""

# -----------------------------
# Parse XML
# -----------------------------
root = ET.fromstring(xml_data)

pages = []
links = {}

for page in root.findall("page"):
    name = page.get("name")
    pages.append(name)

    links[name] = []
    for link in page.findall("link"):
        links[name].append(link.text)

print("Pages:", pages)

# -----------------------------
# Generate Web Graph
# -----------------------------
n = len(pages)
index = {page: i for i, page in enumerate(pages)}

# Adjacency matrix
graph = np.zeros((n, n))

for source in pages:
    for destination in links[source]:
        graph[index[source]][index[destination]] = 1

print("\nWeb Graph (Adjacency Matrix):")
print(graph)

# -----------------------------
# Topic-Specific PageRank
# -----------------------------

# Damping factor
d = 0.85

# Topic preference:
# Here topic is mainly related to pages C and D
topic = np.array([0.0, 0.0, 0.7, 0.3])

# Normalize topic vector
topic = topic / topic.sum()

# Initial PageRank
rank = np.ones(n) / n

# PageRank calculation
for iteration in range(100):

    new_rank = np.zeros(n)

    for i in range(n):

        # Pages pointing to page i
        for j in range(n):
            if graph[j][i] == 1:

                out_links = np.sum(graph[j])

                if out_links > 0:
                    new_rank[i] += rank[j] / out_links

    # Topic-specific PageRank formula
    new_rank = d * new_rank + (1 - d) * topic

    # Check convergence
    if np.linalg.norm(new_rank - rank) < 0.00001:
        break

    rank = new_rank

# -----------------------------
# Display results
# -----------------------------
print("\nTopic-Specific PageRank:")

for i in range(n):
    print(pages[i], ":", round(rank[i], 4))

print("\nIterations:", iteration + 1)

Pages: ['A', 'B', 'C', 'D']

Web Graph (Adjacency Matrix):
[[0. 1. 1. 0.]
 [0. 0. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]]

Topic-Specific PageRank:
A : 0.3631
B : 0.1543
C : 0.3719
D : 0.1106

Iterations: 13
